[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM10
monitor_speed = 115200

[env:esp32dev-ota]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = espota
upload_port = 192.168.1.26
monitor_speed = 115200

upload_flags =
    --auth=YOUR_OTA_PASSWORD
